apiVersion: v1
kind: Service
metadata:
  name: hello-app
  labels:
    app: hello-app
    service: hello-app
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http
      port: 80
  selector:
    app: hello-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app-v1
  labels:
    app: hello-app
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-app
      version: v1
  template:
    metadata:
      labels:
        app: hello-app
        version: v1
    spec:
      containers:
        - name: hello-app
          image: docker.io/nginxdemos/hello
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-public-ingress
spec:
  rules:
    - host: hello{{ .config.local_domain_suffix }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-app
                port:
                  number: 80
