---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nx-cloud-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 1000m
    cert-manager.io/cluster-issuer: local-ca-issuer
  labels:
    app: nx-cloud
spec:
  tls: 
    - hosts:
      - nx-cloud{{ .config.local_domain_suffix }}
      secretName: nx-cloud-cert
  rules:
    - host: nx-cloud{{ .config.local_domain_suffix }}
      http:
        paths:
          - path: /nx-cloud
            pathType: Prefix
            backend:
              service:
                name: nx-cloud-nx-api-service
                port:
                  number: 4203
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: nx-cloud-nrwl-api-service
                port:
                  number: 4000
          - path: /graphql
            pathType: Prefix
            backend:
              service:
                name: nx-cloud-nrwl-api-service
                port:
                  number: 4000
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: nx-cloud-nrwl-api-service
                port:
                  number: 4000
          - path: /download
            pathType: Prefix
            backend:
              service:
                name: nx-cloud-nrwl-api-service
                port:
                  number: 4000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nx-cloud-frontend-service
                port:
                  number: 8080