---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: cloud-mongodb
spec:
  members: 3
  type: ReplicaSet
  version: '6.0.1'
  statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: "mongodb-agent"
              resources:
                requests:
                  cpu: 100m
                  memory: 400M
                limits:
                  cpu: 1000m
                  memory: 500M
            - name: "mongod"
              resources:
                requests:
                  cpu: 100m
                  memory: 500M
                limits:
                  cpu: 1000m
                  memory: 2000M
  security:
    authentication:
      modes: [ 'SCRAM' ]
  users:
    - name: admin-user
      db: nrwl-api
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: admin-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: root
          db: admin
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
---
apiVersion: v1
kind: Secret
metadata:
  name: admin-user-password
type: Opaque
stringData:
  password: changeme
