apiVersion: v1
kind: Secret
metadata:
  name: cloudsecret
type: Opaque
stringData:
  NX_CLOUD_MONGO_SERVER_ENDPOINT: "mongodb+srv://admin-user:changeme@cloud-mongodb-svc.nx-cloud.svc.cluster.local/nrwl-api?replicaSet=cloud-mongodb&ssl=false"
  ADMIN_PASSWORD: "changeme"
  GITHUB_AUTH_CLIENT_ID: "db9339924bda843b95d4"
  GITHUB_AUTH_CLIENT_SECRET: "79d076fd34ffcab442dc2410a1078e46ebd26546"
