apiVersion: v1
kind: Secret
metadata:
  name: cloudsecret
type: Opaque
stringData:
  NX_CLOUD_MONGO_SERVER_ENDPOINT: "mongodb+srv://admin-user:changeme@cloud-mongodb-svc.nx-cloud.svc.cluster.local/nrwl-api?replicaSet=cloud-mongodb&ssl=false"
  ADMIN_PASSWORD: "changeme"
