apiVersion: v1
kind: Secret
metadata:
  name: "local-root-ca"
  namespace: "cert-manager"
data:
  tls.crt: {{ file.Read "rootCA.crt" | base64.Encode }}
  tls.key: {{ file.Read "rootCA.key" | base64.Encode }}
